---

SP-01:
    hostname: 172.16.100.2
    groups:
        - cisco_group
        - north

SP-02:
    hostname: 172.16.100.6
    groups:
         - cisco_group
         - north

LEAF-01:
    hostname: 172.16.100.10
    groups:
        - cisco_group
        - north
 
LEAF-02:
    hostname: 172.16.100.14
    groups:
        - cisco_group
        - north

LEAF-03:
    hostname: 172.16.100.18
    groups:
        - cisco_group
        - south

LEAF-04:
    hostname: 172.16.100.22
    groups:
        - cisco_group
        - south
    
LEAF-05:
    hostname: 172.16.100.26
    groups:
        - cisco_group
        - south
        
LEAF-06:
    hostname: 172.16.100.30
    groups:
        - cisco_group
        - south   
